version: '3.8'

services:
  server:
    build: ./server
    container_name: task-manager-server
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgrespassword@postgres:5432/taskmanager"

  client:
    build: ./client
    container_name: task-manager-client
    ports:
      - "5173:5173"
    depends_on:
      - server

  prisma-studio:
    build: ./server
    container_name: task-manager-studio
    command: ["npx", "prisma", "studio", "--port", "5555", "--browser", "none"]
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgrespassword@postgres:5432/taskmanager"

  postgres:
    image: postgres:15-alpine
    container_name: teema-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: taskmanager
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: